// UATH RELATED ACTIONS
export const AUTH_START = "AUTH_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const RESTORE_TOKEN = "RESTORE_TOKEN";

// TRAVELER RELATED ACTIONS
export const FETCH_TRAVEL_START = "FETCH_TRAVEL_START";
export const FETCH_TRAVEL_SUCCESS = "FETCH_TRAVEL_SUCCESS";
export const FETCH_TRAVEL_FAIL = "FETCH_TRAVEL_FAIL";

// ITEM RELATED ACTIONS
export const FETCH_ITEM_START = "FETCH_ITEM_START";
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_FAIL = "FETCH_ITEM_FAIL";
export const ADD_ITEM = "ADD_ITEM";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";

// CART RELATED ACTIONS
export const FETCH_CART_START = "FETCH_CART_START";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAIL = "FETCH_CART_FAIL";
